---
#cluster-admin-role-binding.yaml
#This cluster-admin-role-binding file assigns a cluster-admin role in kube system namespace to user existing in AAD
#Used for 'kubernetes-dashboard' access
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cmc-cluster-admin-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: clusterroles
  name: cluster-admin
#assign users with emailid which are case senstive or add AAD groups with ObjectID
subjects:
  - kind: Group
    name: 633e1a1c-c2ba-4fd8-b58a-b03fd6b96c9f